export const cities = [
  {
    country: "Andorra",
    geonameid: 3040051,
    name: "les Escaldes",
    subcountry: "Escaldes-Engordany",
  },
  {
    country: "Andorra",
    geonameid: 3041563,
    name: "Andorra la Vella",
    subcountry: "Andorra la Vella",
  },
  {
    country: "United Arab Emirates",
    geonameid: 290594,
    name: "Umm al Qaywayn",
    subcountry: "Umm al Qaywayn",
  },
  {
    country: "United Arab Emirates",
    geonameid: 291074,
    name: "Ras al-Khaimah",
    subcountry: "Ra\u02bcs al Khaymah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 291696,
    name: "Khawr Fakk\u0101n",
    subcountry: "Ash Sh\u0101riqah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292223,
    name: "Dubai",
    subcountry: "Dubai",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292231,
    name: "Dibba Al-Fujairah",
    subcountry: "Al Fujayrah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292239,
    name: "Dibba Al-Hisn",
    subcountry: "Al Fujayrah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292672,
    name: "Sharjah",
    subcountry: "Ash Sh\u0101riqah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292688,
    name: "Ar Ruways",
    subcountry: "Abu Dhabi",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292878,
    name: "Al Fujayrah",
    subcountry: "Al Fujayrah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292913,
    name: "Al Ain",
    subcountry: "Abu Dhabi",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292932,
    name: "Ajman",
    subcountry: "Ajman",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292953,
    name: "Adh Dhayd",
    subcountry: "Ash Sh\u0101riqah",
  },
  {
    country: "United Arab Emirates",
    geonameid: 292968,
    name: "Abu Dhabi",
    subcountry: "Abu Dhabi",
  },
  {
    country: "Afghanistan",
    geonameid: 1120985,
    name: "Zaranj",
    subcountry: "N\u012bmr\u016bz",
  },
  {
    country: "Afghanistan",
    geonameid: 1123004,
    name: "Taloqan",
    subcountry: "Takh\u0101r",
  },
  {
    country: "Afghanistan",
    geonameid: 1125155,
    name: "Sh\u012bn\u1e0fan\u1e0f",
    subcountry: "Herat",
  },
  {
    country: "Afghanistan",
    geonameid: 1125444,
    name: "Shibirgh\u0101n",
    subcountry: "Jowzj\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1125896,
    name: "Shahrak",
    subcountry: "Ghowr",
  },
  {
    country: "Afghanistan",
    geonameid: 1127110,
    name: "Sar-e Pul",
    subcountry: "Sar-e Pol",
  },
  {
    country: "Afghanistan",
    geonameid: 1127628,
    name: "Sang-e Ch\u0101rak",
    subcountry: "Sar-e Pol",
  },
  {
    country: "Afghanistan",
    geonameid: 1127768,
    name: "A\u012bbak",
    subcountry: "Samang\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1128265,
    name: "Rust\u0101q",
    subcountry: "Takh\u0101r",
  },
  {
    country: "Afghanistan",
    geonameid: 1129516,
    name: "Qarq\u012bn",
    subcountry: "Jowzj\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1129648,
    name: "Qar\u0101wul",
    subcountry: "Kunduz",
  },
  {
    country: "Afghanistan",
    geonameid: 1130490,
    name: "Pul-e Khumr\u012b",
    subcountry: "Wil\u0101yat-e Baghl\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1131316,
    name: "Paghm\u0101n",
    subcountry: "Kabul",
  },
  {
    country: "Afghanistan",
    geonameid: 1132495,
    name: "Nahr\u012bn",
    subcountry: "Wil\u0101yat-e Baghl\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1133453,
    name: "Maymana",
    subcountry: "Faryab",
  },
  {
    country: "Afghanistan",
    geonameid: 1133574,
    name: "Mehtar L\u0101m",
    subcountry: "Laghm\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1133616,
    name: "Maz\u0101r-e Shar\u012bf",
    subcountry: "Balkh",
  },
  {
    country: "Afghanistan",
    geonameid: 1134720,
    name: "Lashkar G\u0101h",
    subcountry: "Helmand",
  },
  {
    country: "Afghanistan",
    geonameid: 1135158,
    name: "Kushk",
    subcountry: "Herat",
  },
  {
    country: "Afghanistan",
    geonameid: 1135689,
    name: "Kunduz",
    subcountry: "Kunduz",
  },
  {
    country: "Afghanistan",
    geonameid: 1136469,
    name: "Kh\u014dst",
    subcountry: "Khowst",
  },
  {
    country: "Afghanistan",
    geonameid: 1136575,
    name: "Khulm",
    subcountry: "Balkh",
  },
  {
    country: "Afghanistan",
    geonameid: 1136863,
    name: "Kh\u0101sh",
    subcountry: "N\u012bmr\u016bz",
  },
  {
    country: "Afghanistan",
    geonameid: 1137168,
    name: "Khanabad",
    subcountry: "Kunduz",
  },
  {
    country: "Afghanistan",
    geonameid: 1137807,
    name: "Karukh",
    subcountry: "Herat",
  },
  {
    country: "Afghanistan",
    geonameid: 1138336,
    name: "Kandah\u0101r",
    subcountry: "Kandah\u0101r",
  },
  {
    country: "Afghanistan",
    geonameid: 1138958,
    name: "Kabul",
    subcountry: "Kabul",
  },
  {
    country: "Afghanistan",
    geonameid: 1139715,
    name: "Jal\u0101l\u0101b\u0101d",
    subcountry: "Nangarh\u0101r",
  },
  {
    country: "Afghanistan",
    geonameid: 1139807,
    name: "Jabal os Saraj",
    subcountry: "Parv\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1140026,
    name: "Her\u0101t",
    subcountry: "Herat",
  },
  {
    country: "Afghanistan",
    geonameid: 1141089,
    name: "Ghormach",
    subcountry: "Badghis",
  },
  {
    country: "Afghanistan",
    geonameid: 1141269,
    name: "Ghazni",
    subcountry: "Ghazn\u012b",
  },
  {
    country: "Afghanistan",
    geonameid: 1141540,
    name: "Gereshk",
    subcountry: "Helmand",
  },
  {
    country: "Afghanistan",
    geonameid: 1141857,
    name: "Gard\u0113z",
    subcountry: "Paktia",
  },
  {
    country: "Afghanistan",
    geonameid: 1142170,
    name: "Fayzabad",
    subcountry: "Badakhshan",
  },
  {
    country: "Afghanistan",
    geonameid: 1142264,
    name: "Farah",
    subcountry: "Farah",
  },
  {
    country: "Afghanistan",
    geonameid: 1142404,
    name: "Kafir Qala",
    subcountry: "Herat",
  },
  {
    country: "Afghanistan",
    geonameid: 1145352,
    name: "Charikar",
    subcountry: "Parv\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1147066,
    name: "Barak\u012b Barak",
    subcountry: "Lowgar",
  },
  {
    country: "Afghanistan",
    geonameid: 1147242,
    name: "B\u0101my\u0101n",
    subcountry: "B\u0101m\u012b\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1147290,
    name: "Balkh",
    subcountry: "Balkh",
  },
  {
    country: "Afghanistan",
    geonameid: 1147540,
    name: "Baghl\u0101n",
    subcountry: "Wil\u0101yat-e Baghl\u0101n",
  },
  {
    country: "Afghanistan",
    geonameid: 1148106,
    name: "\u0100rt Khw\u0101jah",
    subcountry: "Takh\u0101r",
  },
  {
    country: "Afghanistan",
    geonameid: 1148205,
    name: "\u0100sm\u0101r",
    subcountry: "Konar",
  },
  {
    country: "Afghanistan",
    geonameid: 1148311,
    name: "Asad\u0101b\u0101d",
    subcountry: "Konar",
  },
  {
    country: "Afghanistan",
    geonameid: 1148658,
    name: "Andkh\u014dy",
    subcountry: "Faryab",
  },
  {
    country: "Afghanistan",
    geonameid: 1429434,
    name: "B\u0101z\u0101rak",
    subcountry: "Panjshir",
  },
  {
    country: "Afghanistan",
    geonameid: 1469706,
    name: "Markaz-e Woluswal\u012b-ye \u0100ch\u012bn",
    subcountry: "Nangarh\u0101r",
  },
  {
    country: "Antigua and Barbuda",
    geonameid: 3576022,
    name: "Saint John\u2019s",
    subcountry: "Saint John",
  },
  {
    country: "Anguilla",
    geonameid: 3573374,
    name: "The Valley",
    subcountry: "N/A",
  },
  {
    country: "Albania",
    geonameid: 363243,
    name: "Sarand\u00eb",
    subcountry: "Vlor\u00eb",
  },
  {
    country: "Albania",
    geonameid: 782661,
    name: "Kuk\u00ebs",
    subcountry: "Kuk\u00ebs",
  },
  {
    country: "Albania",
    geonameid: 782756,
    name: "Kor\u00e7\u00eb",
    subcountry: "Kor\u00e7\u00eb",
  },
  {
    country: "Albania",
    geonameid: 783148,
    name: "Gjirokast\u00ebr",
    subcountry: "Gjirokast\u00ebr",
  },
  {
    country: "Albania",
    geonameid: 783263,
    name: "Elbasan",
    subcountry: "Elbasan",
  },
  {
    country: "Albania",
    geonameid: 783493,
    name: "Burrel",
    subcountry: "Dib\u00ebr",
  },
  {
    country: "Albania",
    geonameid: 3183719,
    name: "Vlor\u00eb",
    subcountry: "Vlor\u00eb",
  },
  {
    country: "Albania",
    geonameid: 3183875,
    name: "Tirana",
    subcountry: "Tiran\u00eb",
  },
  {
    country: "Albania",
    geonameid: 3184081,
    name: "Shkod\u00ebr",
    subcountry: "Shkod\u00ebr",
  },
  {
    country: "Albania",
    geonameid: 3184517,
    name: "Patos Fshat",
    subcountry: "Fier",
  },
  {
    country: "Albania",
    geonameid: 3184862,
    name: "Lushnj\u00eb",
    subcountry: "Fier",
  },
  {
    country: "Albania",
    geonameid: 3184935,
    name: "Lezh\u00eb",
    subcountry: "Lezh\u00eb",
  },
  {
    country: "Albania",
    geonameid: 3185012,
    name: "La\u00e7",
    subcountry: "Lezh\u00eb",
  },
  {
    country: "Albania",
    geonameid: 3185060,
    name: "Ku\u00e7ov\u00eb",
    subcountry: "Berat",
  },
  {
    country: "Albania",
    geonameid: 3185082,
    name: "Kruj\u00eb",
    subcountry: "Durr\u00ebs",
  },
  {
    country: "Albania",
    geonameid: 3185211,
    name: "Kavaj\u00eb",
    subcountry: "Tiran\u00eb",
  },
  {
    country: "Albania",
    geonameid: 3185670,
    name: "Fier-\u00c7if\u00e7i",
    subcountry: "Fier",
  },
  { country: "Albania", geonameid: 3185672, name: "Fier", subcountry: "Fier" },
  {
    country: "Albania",
    geonameid: 3185728,
    name: "Durr\u00ebs",
    subcountry: "Durr\u00ebs",
  },
];
